### ISSUE TITLE
Need to provide a Refresh token flow for long-running processes

### ISSUE THREAD

**Issue by creatovisguru** [ExactTarget/Fuel-Node-Auth#37]
I see we have a getAccessToken, and I haven't tested if I can do it with this implementation, but I know that we have customers and developers who are going to want to be able to instantiate this module and implement a long lived token feature...with minimal effort.

**Comment by kellyjandrews** [comment]
Is this really an issue?

**Comment by vernak2539** [comment]
Nah, closing. No longer supporting long-lived tokens
